version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: software.amazon.awssdk:sdk-core
    versions:
    - "> 2.20.92"
  - dependency-name: software.amazon.awssdk:kms
    versions:
    - "> 1.11.415"
  - dependency-name: org.springframework.cloud:spring-cloud-starter-parent
    versions:
    - "= 2020.0.3"
